version: "3"
services:
  app:
    image: v2fly/v2fly-core:v4.45.2
    network_mode: "host"
    restart: always
    entrypoint: /entrypoint.sh
    command:
      - /usr/bin/app
      - -config
      - /config.json
    volumes:
      - ./config.json:/config.json
      - ./entrypoint.sh:/entrypoint.sh
      - ./ssl/server.crt:/ssl/cert.pem
      - ./ssl/server.key:/ssl/key.pem
